// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBwLTMIQ2z5mcjKHjo9LF8ppmz0UbW3U0',
    appId: '1:732138952968:web:3159cf724a381be66974bd',
    messagingSenderId: '732138952968',
    projectId: 'event-connect-362bb',
    authDomain: 'event-connect-362bb.firebaseapp.com',
    storageBucket: 'event-connect-362bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi831mxpuCkG1BHCVUU-Sa8yxDPkJvHXk',
    appId: '1:732138952968:android:026d779c163579616974bd',
    messagingSenderId: '732138952968',
    projectId: 'event-connect-362bb',
    storageBucket: 'event-connect-362bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkRUpHT1Nqwq1h_N0Jmend5pcbeafvpBg',
    appId: '1:732138952968:ios:8af46e664383fdf56974bd',
    messagingSenderId: '732138952968',
    projectId: 'event-connect-362bb',
    storageBucket: 'event-connect-362bb.firebasestorage.app',
    iosClientId: '732138952968-l2dl76iu1nedlm2d2253f9ff2td0s66f.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventConnect',
  );

}